[global]
address = "localhost"
limits = { forms = 32768 }
template_dir = "themes/moon/views"

[development]
port = 8080
workers = 2
log = "normal"
secret_key = "AvTpuSQErI05xWc5gKSInG09kPGgDqntqgaK1MBxAes="

[production]
port = 9999
workers = 8
log = "critical"
secret_key = "XHx+XBTRvkAuusxom3hfQ/Ql1QNe0rc0nbpLfdmCeHQ="
